### ISSUE TITLE
Doesnt seem to start

### ISSUE THREAD

**Issue by DiamondHawk8** [9P9/Discord-Token-Brute#4]
Upon running the install file and attempting to use the run file, I am met with the message "Press Corrosponding Number to Select Proxy Type to Start!" (Im not even really sure what this means) so I type "1" and the program returns "Starting..." and then nothing happens except for my computer slowing down. Am I doing something wrong?

**Comment by Packjackisback** [comment]
It either doesn't show progress or isn't working, but can confirm it does the same on linux with `npm install` and `node index.js`

**Comment by gagedevs** [comment]
Get working proxies, works fine for me, though I don't know why I thought this might work lmao
